#+begin_export latex
\section{Getting Started}
In this tutorial we use \ty{alfy} to analyze simulated and real
data. To get started, we need to make sure the dependencies are met.
Apart from the programs in the Alfy repo, this tutorial depends on the
coalescent simulator \ty{ms}, the program \ty{ms2dna} for converting
the output of \ty{ms} to DNA sequences, local Blast, the Biobox repo,
and the Bedtools package. Table~\ref{tab:dep} shows where to get these
programs. Make sure they are all in your ``path''.

\begin{table}[ht]
  \caption{Dependencies for this tutorial.}\label{tab:dep}
  \begin{center}
  \scalebox{0.9}{
    \begin{tabular}{lll}
      \hline
      \# & Software & Source\\\hline
      1 & Alfy &
      \href{https://github.com/evolbioinf/alfy}{\ty{github.com/evolbioinf/alfy}}\\
      2 & \ty{ms} &
      \href{https://home.uchicago.edu/rhudson1/source/mksamples.html}{\ty{home.uchicago.edu/rhudson1/source/mksamples.html}}\\
      3 & \ty{ms2dna} &
      \href{http://github.com/evolbioinf/ms2dna}{\ty{github.com/evolbioinf/ms2dna}}\\
      4 & Blast & Package managers like \ty{apt}\\
      5 & Biobox &
      \href{https://github.com/evolbioinf/biobox}{\ty{github.com/evolbioinf/biobox}}\\
      6 & Bedtools & Package managers like \ty{apt}\\\hline
    \end{tabular}
    }
  \end{center}
\end{table}

The directory \ty{playground} inside the \ty{alfy} repo contains all
the necessary files for following the tutorial. Please change into
\ty{playground}.

\section{Simulated Data}
We begin by simulating single crossover events before we generalize
this to multiple crossovers.
\subsection*{Single Crossover}
The program \ty{cross.sh} simulates single crossover events between
two subject sequences to generate one query sequence. By default, the
three sequences are 10\,kb long and the crossover event is in the
middle. So we get the result illustrated in Figure~\ref{fig:hom},
where the first 5\,kb of the query are more closely related to $s_1$,
the rest is more closely related to $s_2$. We print the help message
of \ty{cross.sh}
#+end_export
#+begin_src sh <<sda.sh>>=
  bash cross.sh -h
#+end_src
#+begin_export latex
\begin{verbatim}
Usage: bash cross.sh [-h] [option]...
Simulate single midpoint crossover between
   two subjects in s.fasta and one query in q.fasta.
Example: bash cross.sh -s 3
   -l int
        sequence length (default 10000)
   -m float
        mutation rate before crossover (default 0.1)
   -M float
        mutation rate after crossover (default 0.01)
   -s int
        seed (default random integer)
\end{verbatim}
\begin{figure}
  \begin{center}
  \hspace{-5cm}
    \begin{tabular}{cc}
      $q$ & \psline[linewidth=2pt,linecolor=red](0,0)(2.5,0)
      \psline[linewidth=2pt,linecolor=blue](2.5,0)(5,0)\\
      $s_1$ & \psline[linewidth=2pt,linecolor=red](0,0)(5,0)\\
      $s_2$ & \psline[linewidth=2pt,linecolor=blue](0,0)(5,0)\\
      & \psline{<->}(0,0)(5,0)\\
      & \rput(2.5,0){10\,kb}
    \end{tabular}
  \end{center}
  \caption{A query sequence, $q$ and two subject sequences, $s_1$ and
    $s_2$, all 10\,kb long; matching colors indicate homology.}\label{fig:hom}
\end{figure}

We run \ty{cross.sh} with default parameters to get the query file
\ty{q.fasta} and the subject file \ty{s.fasta}.
#+end_export
#+begin_src sh <<sda.sh>>=
  bash cross.sh
#+end_src
#+begin_export latex
We run \ty{alfy} on the query and the subjects we just generated to
find that the expected crossover point at position 5000 is reasonably
well detected.
#+end_export
#+begin_src sh <<sda.sh>>=
  alfy -i q.fasta -j s.fasta
#+end_src
#+begin_export latex
\begin{verbatim}
>q
1	4875	  82.6	s_1
4876	10000	 100.7	s_2
\end{verbatim}
#+end_export
#+begin_export latex
We can repeat this simulation in a loop to find that the result is
quite stable.
#+end_export
#+begin_src sh <<sda.sh>>=
  for a in $(seq 20); do
      bash cross.sh
      alfy -i q.fasta -j s.fasta |
	  tail -n 2
  done
#+end_src
#+begin_export latex
\begin{verbatim}
1       4995     109.4  s_1
4996    10000     95.6  s_2
1       4905     106.0  s_1
4906    10000     80.6  s_2
1       4995      81.2  s_1
4996    10000     82.1  s_2
...
\end{verbatim}
#+end_export
#+begin_export latex
\subsection*{Multiple Crossovers}
The simulation scenario implemented in \ty{cross.sh} is rather
simple. For a more thorough exploration of \ty{alfy} we need to be
able to simulate more diverse datasets. Figure~\ref{fig:wf} shows our
workflow for this. It starts with population genetic parameters, which
are transformed by the script \ty{neiSim.sh} into three files:
haplotypes in \ty{haplotypes.ms}, a corresponding query sequence in
\ty{query.fasta}, and two or more corresponding subject sequences in
\ty{subjects.fasta}. From the sequence data \ty{alfy} calculates the
observed annotations, while \ty{ms2nn} extracts the expected
annotations from the haplotypes. Finally, the observed and expected
results are compared to calculate the accuracy, $a$.

\begin{figure}[ht]
  \begin{center}
    \input{../tut/wf}
  \end{center}
\caption{Workflow for calculating the accuracy, $a$, of \ty{alfy}
  (red); auxiliary programs in blue.}\label{fig:wf}
\end{figure}

In the following, we first familiarize ourselves with the individual
steps of the workflow in Figure~\ref{fig:wf}, before we summarize them
into the script \ty{testAlfy.sh}. We begin by printing the help
message of \ty{neiSim.sh}.
#+end_export
#+begin_src sh <<sda.sh>>=
  bash neiSim.sh -h
#+end_src
#+begin_export latex
\begin{verbatim}
Usage: bash neiSim.sh [-h] [option]...
Neighbors simulation as one query in
        query.fasta and one or more subjects
        in subjects.fasta; the underlying
        haplotypes are in haplotypes.ms.
Example: bash neiSim.sh -n 5 -t 50 -r 1
   -n int
        sample size (default 3)
   -t float
        theta (default 100)
   -r float
        rho (default 0)
   -l int
        sequence length (default 10000)
   -s int
        seed (default random integer)
\end{verbatim}
#+end_export
#+begin_export latex
We run \ty{neiSim.sh} with default options, i. e. no recombination,
except for the seed for the random number generator, which we set to 1
to make the simulation reproducible.
#+end_export
#+begin_src sh <<sda.sh>>=
  bash neiSim.sh -s 1
#+end_src
#+begin_export latex
When we run \ty{alfy} on the query and subject sequences we just
generated, we get sequence 3 as the closest neighbor for regions
1--1515 and 1666--10000, that is for 9850, or 98.5\,\%, of the
10000\,bp input. The interspersed 150\,bp are diagnosed as being most
closely related by subject 2.
#+end_export
#+begin_src sh <<sda.sh>>=
  alfy -i query.fasta -j subjects.fasta
#+end_src
#+begin_export latex
\begin{verbatim}
>1
1       1515         948.7      3
1516    1665         400.7      2
1666    10000       4024.7      3
\end{verbatim}
#+end_export
#+begin_export latex
If we use \ty{ms2nn} to extract the true closest neighbor from the
simulated haplotypes, we just get 3. In addition to the closest
neighbor, \ty{ms2nn} also tells us that sequences 1 and 3 differ at
0.0002 positions per site. For our 10\,kb sequence this implies a mere
2 mismatches.
#+end_export
#+begin_src sh <<sda.sh>>=
ms2nn -q 1 haplotypes.ms
#+end_src
#+begin_export latex
\begin{verbatim}
>1
1	10000	0.0002	3
\end{verbatim}
#+end_export
#+begin_export latex
We can also use Blast to confirm that sequence 3 is separated from
sequence 1 by 2 mismatches, while it is separated from sequence 2 by
59 mismatches, 29 times as many.
#+end_export
#+begin_src sh <<sda.sh>>=
  blastn -query query.fasta -subject subjects.fasta \
	 -outfmt 6 |
      column -t
#+end_src
#+begin_export latex
\small
\begin{verbatim}
1  3  99.980  10000  2   0  1  10000  1  10000  0.0  18456
1  2  99.410  10000  59  0  1  10000  1  10000  0.0  18140
\end{verbatim}
\normalsize
So far, so good. Let's simulate another set of haplotypes by changing
the seed of the random number generator.
#+end_export
#+begin_src sh <<sda.sh>>=
  bash neiSim.sh -s 2
#+end_src
#+begin_export latex
Now the \ty{alfy} result fluctuates much more between 2 and 3, even
though we know that no recombination has taken place. We save the
output to \ty{alfy.out}.
#+end_export
#+begin_src sh <<sda.sh>>=
  alfy -i query.fasta -j subjects.fasta |
      tee alfy.out
#+end_src
#+begin_export latex
\begin{verbatim}
>1
1       5535       1203.4       2
5536    6165        735.2       3
6166    7245       1034.5       2
7246    8685        833.2       3
8686    10000       535.7       2
\end{verbatim}
#+end_export
#+begin_export latex
We quantify the genotypes in the \ty{alfy} output to find that 79\,\%
of the query is annotated as having closest neighbor 2, the remaining
21\,\% as having closest neighbor 3.
#+end_export
#+begin_src sh <<sda.sh>>=
  awk -f quantifyGenotypes.awk alfy.out
#+end_src
#+begin_export latex
\begin{verbatim}
>1
2       79.3
3       20.7
\end{verbatim}
Sequence 2 is also the ``true'' result as given by \ty{ms2nn}.
#+end_export
#+begin_src sh <<sda.sh>>=
  ms2nn -q 1 haplotypes.ms
#+end_src
#+begin_export latex
\begin{verbatim}
>1
1	10000	0.0006	2
\end{verbatim}
#+end_export
#+begin_export latex
It is well known that local fluctuations in the mutation density can
lead to local fluctuations of nearest neighbors even in the absence of
recombination. With Blast we can see that the local annotations of
\ty{alfy} are correct for all five intervals in this particular
example.
#+end_export
#+begin_src sh <<sda.sh>>=
  printf "Alfy\tBlast\n"
  tail -n +2 alfy.out |
      while read start end score anno; do
	  printf "$anno\t"
	  cutSeq -r $start-$end query.fasta > f.fasta
	  blastn -query f.fasta -subject \
		 subjects.fasta -outfmt 6 |
	      head -n 1 |
	      cut -f 2
      done
#+end_src
#+begin_export latex
\begin{verbatim}
Alfy    Blast
2       2
3       3
2       2
3       3
2       2
\end{verbatim}
#+end_export
#+begin_export latex
We now add recombination to the simulation.
#+end_export
#+begin_src sh <<sda.sh>>=
  bash neiSim.sh -r 1 -s 3
#+end_src
#+begin_export latex
The neighbors again fluctuate along the query, where for each
recombining fragment, \ty{ms2nn} picks the closest subject. This
constitutes our ``expected'' result, and we store it in file
\ty{exp.txt}.
#+end_export
#+begin_src sh <<sda.sh>>=
  ms2nn -q 1 haplotypes.ms |
      tee exp.txt
#+end_src
#+begin_export latex
\begin{verbatim}
>1
1       6874    0.0095  3
6875    7444    0.0105  2
7445    8130    0.0131  3
8131    10000   0.0144  2
\end{verbatim}
#+end_export
#+begin_export latex
This fluctuation is traced by \ty{alfy}, albeit not perfectly. The
\ty{alfy} output constitutes our ``observed'' results and we store
them in file \ty{obs.txt}.
#+end_export
#+begin_src sh <<sda.sh>>=
  alfy -i query.fasta -j subjects.fasta |
      tee obs.txt
#+end_src
#+begin_export latex
\begin{verbatim}
>1
1       6735      92.2  3
6736    7455      89.7  2
7456    8145      84.3  3
8146    10000     53.5  2
\end{verbatim}
We quantify the accuracy of \ty{alfy} as the fraction of correctly
annotated query positions as implemented in the Awk script
\ty{accuracy.awk}. We apply this to our expected and observed results to
find $a=0.98$.
#+end_export
#+begin_src sh <<sda.sh>>=
  awk -f accuracy.awk -v e=exp.txt -v o=obs.txt
#+end_src
#+begin_export latex
We now have all the parts in hand for carrying out a systematic
exploration of the accuracy of \ty{alfy}. For this we run the four
programs in Figure~\ref{fig:wf} in the script
\ty{testAlfy.sh}. \bpr{testAlfy.sh}{pr:ta}
#+end_export
#+begin_src sh <<testAlfy.sh>>=
  ##<<Run \ty{neiSim.sh}, Pr. \ref{pr:ta}>>
  ##<<Run \ty{alfy}, Pr. \ref{pr:ta}>>
  ##<<Run \ty{ms2nn}, Pr. \ref{pr:ta}>>
  ##<<Run \ty{accuracy.awk}, Pr. \ref{pr:ta}>>
#+end_src
#+begin_export latex
\epr
We run \ty{neiSim.sh} with the parameters we have used so far, except
for the seed for the random number generator, which we leave blank to
generate independent runs. But the parameters can be set to any
scenario we might like to simulate, of course.
#+end_export
#+begin_src sh <<Run \ty{neiSim.sh}, Pr. \ref{pr:ta}>>=
  bash neiSim.sh -n 3 \
       -t 100 \
       -r 1 \
       -l 10000
#+end_src
#+begin_export latex
We run \ty{alfy} on the sequences simulated by \ty{neiSim.sh} and save
the result to \ty{obs.txt}.
#+end_export
#+begin_src sh <<Run \ty{alfy}, Pr. \ref{pr:ta}>>=
  alfy -i query.fasta -j subjects.fasta > obs.txt
#+end_src
#+begin_export latex
We use \ty{ms2nn} to extract the expected results from the haplotypes.
#+end_export
#+begin_src sh <<Run \ty{ms2nn}, Pr. \ref{pr:ta}>>=
  ms2nn -q 1 haplotypes.ms > exp.txt
#+end_src
#+begin_export latex
We calculate the accuracy from the observed and expected results.
#+end_export
#+begin_src sh <<Run \ty{accuracy.awk}, Pr. \ref{pr:ta}>>=
  awk -f accuracy.awk -v e=exp.txt -v o=obs.txt
#+end_src
#+begin_export latex
Now we can run \ty{testAlfy.sh} in a loop to observe that its accuracy
fluctuates quite widely under the simulated scenario.
#+end_export
#+begin_src sh <<sda.sh>>=
  for a in $(seq 100); do
      bash testAlfy.sh
  done
#+end_src
#+begin_export latex
\begin{verbatim}
0.7690
0.9400
0.6623
0.5575
0.4716
...
\end{verbatim}
#+end_export
#+begin_export latex
The script \ty{testAlfy.sh} could now be modified to test \ty{alfy}
under diverse evolutionary scenarios. However, in this tutorial we
move on to look at real data.
\section{Real Data}
Our analysis of real data is centered on HIV genomes. We annotate the
query strain \ty{A+\-DQ\-083238} using the 42 pure strains stored in
\ty{hiv42.fasta} as subject.
#+end_export
#+begin_src sh <<eda.sh>>=
  cp ../data/A+DQ083238.fasta .
  cp ../data/hiv42.fasta .
#+end_src
#+begin_export latex
We analyze the query with \ty{alfy}.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -i A+DQ083238.fasta -j hiv42.fasta
#+end_src
#+begin_export latex
\begin{verbatim}
>A+DQ083238
1       225       8.6   A1+AF004885
226     495      25.1   A1+AF069670
...
8806    9330      8.9   A1+AF004885
9331    9699     15.8   A1+U51190
\end{verbatim}
This means that positions 1--225 of A+DQ083238 are most closely
related to strain A1+AF004885. Further, across that interval the
average shustring length of the shustrings induced by the ``winning''
subject sequence---A1+AF004885 in this case---is 8.6, which is a
measure of the strength of the homology signal across that interval.

To get a clearer view of the distribution of the various annotations,
we again use \ty{quantifyGenomes.awk} to summarize the \ty{alfy}
output.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -i A+DQ083238.fasta -j hiv42.fasta  | 
      awk -f quantifyGenotypes.awk
#+end_src
#+begin_export latex
\begin{verbatim}
>A+DQ083238
A1+AF004885  38.0
A1+AF069670  11.4
..
G+AF061642   1.9
A2+AF286238  1.5
\end{verbatim}
This indicates that 38.0\% of strain A+DQ083238 is most closely
related to strain A1+AF004885, 11.4\% to strain C+AF067155, etc.

We further summarize the result by collapsing annotations for strains
that belong to the same group.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -i A+DQ083238.fasta -j hiv42.fasta  | 
      sed 's/+.*//' | 
      awk -f quantifyGenotypes.awk
#+end_src
#+begin_export latex
\begin{verbatim}
>A
A1  64.6
C   24.7
G   6.3
D   2.8
A2  1.5
\end{verbatim}
The program \ty{alfy} works in three steps:
\be
\I Construct enhanced suffix array from all query and
subject sequences;
\I determine ``winning'' subjects across contiguous intervals
along a query;
\I carry out sliding window analysis of these closest neighbors intervals to
find the final annotation of a given query.
\ee
The last step is sensitive to the length of the sliding window. By
default this is 300 bp; if we set it to 400 bp, the results
change somewhat, but not dramatically.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -w 400 -i A+DQ083238.fasta -j hiv42.fasta  | 
      sed 's/+.*//' | 
      awk -f quantifyGenotypes.awk
#+end_src
#+begin_export latex
\begin{verbatim}
>A
A1  63.1
C   26.8
G   7.6
D   2.5
\end{verbatim}

We may only be interested in ``strong'' homology signals in our
analysis. These are defined as regions where the average shustring
length is greater than the maximum shustring length occurring by
chance alone. Regions with an average shustring length below the
threshold value are marked \ty{nh} for ``no homology''.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -i A+DQ083238.fasta -j hiv42.fasta -M
#+end_src
#+begin_export latex
\begin{verbatim}
>A+DQ083238
1       225       8.6   A1+AF004885
226     495      25.1   A1+AF069670
...
8836    9330      9.1   A1+AF004885
9331    9699     15.8   A1+U51190
\end{verbatim}

As before, we summarize the annotations and find that the K annotation
is now missing altogether and 8.7\% of the annotations are revealed as
``weak'' (\ty{nh}).
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -i A+DQ083238.fasta -j hiv42.fasta -M |
      sed 's/+.*//' | 
      awk -f quantifyGenotypes.awk
#+end_src
#+begin_export latex
\begin{verbatim}
>A
A1  57.5
C   24.7
nh  8.7
G   6.3
D   2.8
\end{verbatim}

To further investigate what an \ty{nh} annotation means, we can
extract such a region and blast it against the 42 subject
sequences. As expected, this returns only weak homologues.
#+end_export
#+begin_src sh <<eda.sh>>=
  cutSeq -r 6556-6705 A+DQ083238.fasta > nh.fasta
  blastn -query nh.fasta -subject hiv42.fasta -outfmt 6  
#+end_src
#+begin_export latex
\scriptsize
\begin{verbatim}
A+DQ083238  A1+AF069670  78.698  169  15  10  1  148  5770  5938  3.71e-21  93.5
A+DQ083238  B+AY173951   93.333  60   4   0   1  60   5903  5962  4.79e-20  89.8
A+DQ083238  J+AF082395   87.838  74   9   0   1  74   5877  5950  1.72e-19  87.9
A+DQ083238  K+AJ249239   88.710  62   7   0   1  62   5756  5817  3.73e-16  76.8
\end{verbatim}
\normalsize

The amount of weakly homologous regions is sensitive to the minimal
length of a recombining fragment. This quantity is set by the \ty{-f}
option with a default value of $\ty{-w}/4=75$. Increasing this value
leads to fewer regions diagnosed as ``non homologous''. For example,
if we double the value of \ty{-f}, we get none.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -f 150 -i A+DQ083238.fasta -j hiv42.fasta -M |
      sed 's/+.*//' | 
      awk -f quantifyGenotypes.awk
#+end_src
#+begin_export latex
\begin{verbatim}
>A
A1  64.0
C   24.7
G   8.5
D   2.8
\end{verbatim}

The previous result is again sensitive to the parameter settings. In
this case the central quantity is the significance value for the
maximum shustring length. The mathematical theory for this was derived
in~\cite{hau09:est} and it is set with the \ty{-P} option. This can be
interpreted like a classical $P$-value: it is the error probability
when rejecting the null hypothesis that a shustring of some given
length is due to chance alone. The default value of the \ty{-P} option
is 0.4, which may strike you as rather high---why not use the
classical $P=0.05$ threshold? It is important to realize that a query
has to contain not just one shustring that is longer than the maximum
shustring length, but this property has to apply on average to
\textit{all} shustrings across a given window. If we set \ty{-P} to a
much more stringent value like 0.05, almost a quarter of the query is
annotated as non-homologous, most likely an overestimate.
#+end_export
#+begin_src sh <<eda.sh>>=
  alfy -i A+DQ083238.fasta -j hiv42.fasta -M -P 0.05 | 
      sed 's/+.*//' | 
      awk -f quantifyGenotypes.awk
#+end_src
#+begin_export latex
\begin{verbatim}
>A
A1  44.2
nh  23.8
C   22.7
G   6.3
D   2.9
\end{verbatim}
#+end_export
