#+begin_export latex
\section{Introduction}
The program \ty{ms2nn} takes as input the output of the coalescent
simulation program \ty{ms} and prints the nearest neighbors for a
given query. This output can then be compared to the output of
programs for identifying nearest neighbors, for example
\ty{alfy}. Figure~\ref{fig:ms} shows a sketch of the intended
workflow. The program \ty{ms} is used to convert population genetic
parameters into a sample of haplotypes. The haplotypes are converted
to DNA sequences using the program
\ty{ms2dna}\footnote{\ty{https://github.com/evolbioinf/ms2dna}}. These
DNA sequences are analyzed with \ty{alfy} to get a set of estimated
nearest neighbors. In a second analysis strand the original haplotypes
are converted by \ty{ms2nn} to the true nearest neighbors. Now the
estimated and true nearest neighbors can be compared.

\begin{figure}[ht]
\begin{center}
\scalebox{0.66}{\input{../ms2nn/ms}}
\end{center}
\caption{Workflow for testing the nearest neighbor predictions
  produced by \ty{alfy} using \ty{ms2nn}; ideally, the nearest
  neighbors estimated by \ty{alfy} are identical to the true nearest
  neighbors.}\label{fig:ms}
\end{figure}

Any \ty{ms} command to generate a sample of haplotypes requires tree
printing and recombination among the number of sites that will be
turned into nucleotides later by \ty{ms2dna}. For example, here is a
command to generate one tiny sample of three haplotypes with two
segregating sites (\ty{-s}), recombination rate $\rho=1$ among 100
recombining units---think base pairs---(\ty{-r}), and tree printing
(\ty{-T}):
\begin{verbatim}
ms 3 1 -s 2 -r 1 100 -T
\end{verbatim}
This command might generate the output shown in Figure~\ref{fig:mso}
with additional line numbering.
\begin{figure}
  \begin{center}
  \fbox{
      \begin{tabular}{rl}
 1  & \ty{ms 3 1 -s 2 -r 1 100 -T}\\
 2  & \ty{45133 4835 14524}\\
 3  &\\
 4  & \ty{//}\\
 5  & \ty{[11](2:0.544,(1:0.482,3:0.482):0.063);}\\
 6  & \ty{[46](3:0.939,(1:0.544,2:0.544):0.395);}\\
 7  & \ty{[43](3:1.107,(1:0.544,2:0.544):0.563);}\\
 8  & \ty{segsites: 2}\\
 9  & \ty{positions: 0.2966 0.7152}\\
10  & \ty{10}\\
11  & \ty{00}\\
12  & \ty{01}\\
\end{tabular}
}
  \end{center}
  \caption{Sample output from \ty{ms}.}\label{fig:mso}
\end{figure}
The first line echoes the \ty{ms} command, of which the sample size and
the sequence length of the \ty{-r} flag, and the \ty{-T} flag are relevant for the
subsequent analysis. The second line gives the seeds for the random
number generator that can be used to reproduce this run by appending
the \ty{-seeds} flag to the command to give
\begin{verbatim}
ms 3 1 -s 2 -r 1 100 -T -seeds 45133 4835 14524
\end{verbatim}

The third line is blank, and the double forward slashes on the fourth
line indicates the start of a sample. The next three lines contain
trees. Unless the recombination rate is zero, trees start with their
extent along the sequence in square brackets. They always end with a
semi colon. So the first tree extends from position 1--11 along the
sequence, the second along the next 46 positions between 12 and 57, and the
third along the remaining 43 positions 58--100. Notice that the three
trees differ both in topology and branch lengths. Let's concentrate on
the topology. The first tree has topology ((1,3)2) and thus groups 3
with 1. The second has topology ((1,2)3) and thus groups 2 with 1, as
does the third tree.

\begin{figure}
\begin{center}
\input{../ms2nn/tree}
\end{center}
\caption{A sketch of the tree toplologies along the haplotype sample
  consisting of 100 recombining units in Figure~\ref{fig:ms};
  mutations are shown in red.}\label{fig:tree}
\end{figure}

Line 8 says there are two segregating sites, or mutations, in the
sample. In line 9 the two segregating sites are listed by their
``positions'' along the unit interval $(0,1)$, 0.2966 and
0.7152. Along the sequence these positions are 30 and 72 as marked in
red in Figure~\ref{fig:tree}. The three haplotypes of zeros and ones
in the last three lines are the basis for calculating distances to the
query.

As shown in Figure~\ref{fig:tree}, the first tree contains no
mutations, so the two distances from 1 to its neighbors are both
zero. This means the closest neighbors are 2 and 3. Notice that this
is different from the topological nearest neighbor, 2. The stochastic
nature of mutations means that such contradictions between tree
topology and distances are common.

The second tree contains the first polymorphism mutation at position
30. This mutation happened along the branch leading to 1, which means
that its closest neighbors are again 2 and 3, this time with a
distance of one mismatch (Figure~\ref{fig:tree}). Since the first two
sets of nearest neighbors agree, they are merged into a single
annotation. The third tree contains the second polymorphism at
position 72. This mutation happened along the branch leading to 3. As
a result, query 1 is closer to 2 than to 3, so its closest neighbor
changes to 2.

The program \ty{ms2nn} parses the \ty{ms} output and for a given query
finds its nearest neighbors for each tree. The results are printed as
pseudo-\ty{alfy} output, which starts with a FASTA header giving the
name of the query, followed by a tab-separated table of four columns
consisting of start, end, score, and one or more annotations separated
by blanks. For example, if we apply \ty{ms2nn} to the data in
Figure~\ref{fig:mso}, we get
\begin{verbatim}
>1
1       57      0.0175  2 3
58      100     0.0000  2
\end{verbatim}
This means that for sequence positions 1--57, sequence 1 has closest
neighbors 2 and 3 with a distance of $1/57\approx 0.0175$ mutations
per site. For positions 72--100 the closest neighbor of 1 is 2, and
the two sequences are identical.

For simplicity, \ty{ms2nn} outputs the tree boundaries to delimit the
annotations, even though they cannot be discovered from the
data. Still, a search for the interval $(1,57)$ from sequence 1 would
confirm that sequences 2 and 3 are neighbors with distance 0.0175.

Instead of picking the nearest neighbors by distance, the user can
also opt for getting the ``true'' neighbors as read from the tree
topology. If we apply \ty{ms2nn} to the same data with tree analysis
instead of distance analysis, we get
\begin{verbatim}
>1
1       11      -1.0000 3
12      100     -1.0000 2
\end{verbatim}
Now the topologically identical last two trees are merged into one
annotation that extends from position 12 to the end
(Figure~\ref{fig:tree}).  To remind the user that these neighbors were
not determined from distances, the distances are set to a nonsensical
value, -1.

\section{Implementing \ty{ms2nn}}
Our outline of \ty{ms2nn} has hooks for imports, functions, and the
logic of the main function.
\bpr{ms2nn}{pr:m2n}
#+end_export
#+begin_src go <<ms2nn.go>>=
  package main

  import (
	  //<<Imports, Pr. \ref{pr:m2n}>>
  )
  //<<Types, Pr. \ref{pr:m2n}>>
  //<<Functions, Pr. \ref{pr:m2n}>>
  func main() {
	  //<<Main function, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
\epr In the main function we prepare the log package for error
messages from \ty{ms2nn}, set the usage, declare the flags, parse
the flags, and parse the input.
#+end_export
#+begin_src go <<Main function, Pr. \ref{pr:m2n}>>=
  clio.PrepLog("ms2nn")
  //<<Set usage, Pr. \ref{pr:m2n}>>
  //<<Declare flags, Pr. \ref{pr:m2n}>>
  //<<Parse flags, Pr. \ref{pr:m2n}>>
  //<<Parse input, Pr. \ref{pr:m2n}>>
#+end_src
#+begin_export latex
We import \ty{clio}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
The usage consists of three parts, the usage proper, an explanation of
the purpose of \ty{ms2nn}, and an example command. To design the
usage, we note that there is no sensible default for the query, so we
make it a mandatory flag.
#+end_export
#+begin_src go <<Set usage, Pr. \ref{pr:m2n}>>=
  u := "ms2nn -q <query> [option]... [foo.ms]..."
  p := "Convert the output of ms to alfy output."
  e := "ms 5 1 -t 100 -r 100 10000 -T | ms2nn -q 1"
  clio.Usage(u, p, e)
#+end_src
#+begin_export latex
Apart from the customary version, \ty{-v}, we declare two flags, the
query, \ty{-q}, and tree analysis rather than distance analysis for
getting the neighbors, \ty{-t}.
#+end_export
#+begin_src go <<Declare flags, Pr. \ref{pr:m2n}>>=
  flagV := flag.Bool("v", false, "version")
  flagQ := flag.String("q", "", "query")
  flagT := flag.Bool("t", false, "tree analysis " +
	  "(default distance analysis)")
#+end_src
#+begin_export latex
We import \ty{flag}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "flag"
#+end_src
#+begin_export latex
We parse the flags and respond to the version and query flags.
#+end_export
#+begin_src go <<Parse flags, Pr. \ref{pr:m2n}>>=
  flag.Parse()
  //<<Respond to \ty{-v}, Pr. \ref{pr:m2n}>>
  //<<Respond to \ty{-q}, Pr. \ref{pr:m2n}>>
#+end_src
#+begin_export latex
We print the version upon request.
#+end_export
#+begin_src go <<Respond to \ty{-v}, Pr. \ref{pr:m2n}>>=
  if *flagV {
	  util.Version("ms2nn")
  }
#+end_src
#+begin_export latex
We import \ty{util}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "github.com/evolbioinf/alfy/util"
#+end_src
#+begin_export latex
If the user didn't set a query, something is wrong and we abort with a
friendly message.
#+end_export
#+begin_src go <<Respond to \ty{-q}, Pr. \ref{pr:m2n}>>=
  if *flagQ == "" {
	  log.Fatal("please use -q to enter a query")
  }
#+end_src
#+begin_export latex
We import \ty{log}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "log"
#+end_src
#+begin_export latex
The remaining arguments on the command line are interpreted as file
names. Each file is parsed by the function \ty{parse}, which in turn
takes as argument the query and the tree analysis flags.
#+end_export
#+begin_src go <<Parse input, Pr. \ref{pr:m2n}>>=
  files := flag.Args()
  clio.ParseFiles(files, parse, *flagQ, *flagT)
#+end_src
#+begin_export latex
Inside the function \ty{parse}, we retrieve the arguments, prepare the
storage, and iterate over the input to store the data. From the stored
data we find the query's neighbors per tree. As explained above, trees
may have identical neighbors, in which case we merge their intervals,
before we print the neighbors.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:m2n}>>=
  func parse(r io.Reader, args... interface{}) {
	  //<<Retrieve arguments, Pr. \ref{pr:m2n}>>
	  //<<Prepare storage, Pr. \ref{pr:m2n}>>
	  sc := bufio.NewScanner(r)
	  for sc.Scan() {
		  //<<Store data, Pr. \ref{pr:m2n}>>
	  }
	  //<<Find neighbors, Pr. \ref{pr:m2n}>>
	  //<<Merge trees, Pr. \ref{pr:m2n}>>
	  //<<Print neighbors, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
We import \ty{io} and \ty{bufio}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "io"
  "bufio"
#+end_src
#+begin_export latex
We retrieve two arguments, query and tree analysis. The query is a
string denoting an integer, which serves as index into the slice of
haplotypes. So we also convert it to its integer value. The input
integer is one-based, but indexes are zero-based, so we make the query
index zero-based, too.
#+end_export
#+begin_src go <<Retrieve arguments, Pr. \ref{pr:m2n}>>=
  query := args[0].(string)
  treeAnalysis := args[1].(bool)
  qi, err := strconv.Atoi(query)
  util.Check(err)
  qi = qi - 1
#+end_src
#+begin_export latex
We import \ty{strconv}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "strconv"
#+end_src
#+begin_export latex
\subsection*{Store \ty{ms} Output}
To store the output from \ty{ms}, we need storage for the sample size,
the sequence length, the trees, the positions of mutations, and the
haplotypes. We also declare a variable for the tree start position,
which we initialize to the position implied by \ty{ms}, 1. In the
zero-based world of Go this means 0.
#+end_export
#+begin_src go <<Prepare storage, Pr. \ref{pr:m2n}>>=
  var nsam, seqLen int
  trees := []*Tree{}
  positions := []float64{}
  haplotypes := []string{}
  start := 0
#+end_src
#+begin_export latex
If the current line is empty, there is no data to store and we skip
the line. Otherwise we classify it by its first or last character.
#+end_export
#+begin_src go <<Store data, Pr. \ref{pr:m2n}>>=
  line := sc.Text()
  if len(line) == 0 {
	  continue
  }
  fc := line[0]
  lc := line[len(line)-1]
  //<<Classify line, Pr. \ref{pr:m2n}>>
#+end_src
#+begin_export latex
The line can be one of four things
\begin{enumerate}
\item the original \ty{ms} command starting with ``m'', in which case
  we analyze it
\item a tree ending with ``;``, in which case we store it
\item a row of positions of mutations starting with ``p'', in which
  case we store them
\item a row of polymorphisms starting with ``0'' or ``1'' and not
  containing any blanks (else it might be the seed), in which case we
  store the resulting haplotype
\end{enumerate}
#+end_export
#+begin_src go <<Classify line, Pr. \ref{pr:m2n}>>=
  if fc == 'm' {
	  //<<Analyze command, Pr. \ref{pr:m2n}>>
  } else if lc == ';' {
	  //<<Store tree, Pr. \ref{pr:m2n}>>
  } else if fc == 'p' {
	  //<<Store positions of mutations, Pr. \ref{pr:m2n}>>
  } else if (fc == '1' || fc == '0') &&
	  strings.Index(line, " ") == -1 {
	  //<<Store haplotype, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
Recall that an \ty{ms} command looks like this,
\begin{verbatim}
ms 3 1 -s 2 -r 1 100 -T
\end{verbatim}
of which we need the sample size, 3, the sequence length, 100, and
tree printing, \ty{-T}. Since tree printing is necessary for
\ty{ms2nn} to work, we check this first. Then we get the sample size
and the sequence length.
#+end_export
#+begin_src go <<Analyze command, Pr. \ref{pr:m2n}>>=
  //<<Check tree printing, Pr. \ref{pr:m2n}>>
  //<<Get sample size, Pr. \ref{pr:m2n}>>
  //<<Get sequence length, Pr. \ref{pr:m2n}>>
#+end_src
#+begin_export latex
If the user did not switch on tree printing, something is wrong and we
exit with a friendly message.
#+end_export
#+begin_src go <<Check tree printing, Pr. \ref{pr:m2n}>>=
  if strings.Index(line, "-T") < 0 {
	  log.Fatal("please use tree printing, -T")
  }
#+end_src
#+begin_export latex
We split the command into its fields. The sample size is the second
field.
#+end_export
#+begin_src go <<Get sample size, Pr. \ref{pr:m2n}>>=
  fields := strings.Fields(line)
  nsam, err = strconv.Atoi(fields[1])
  util.Check(err)
#+end_src
#+begin_export latex
We import \ty{strings}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "strings"
#+end_src
#+begin_export latex
The sequence length is the second of the arguments of \ty{-r}.
#+end_export
#+begin_src go <<Get sequence length, Pr. \ref{pr:m2n}>>=
  for i := 3; i < len(fields); i++ {
	  if fields[i] == "-r" {
		  seqLen, err =
			  strconv.Atoi(fields[i+2])
		  util.Check(err)
	  }
  }
#+end_src
#+begin_export latex
The next thing we store is a tree. A tree refers to an interval that
has a start and an end. These start and end positions imply start and
end indexes in a haplotype array. The tree also contains neighbors and
mismatches with respect to a query. The tree itself is stored as its
root.
#+end_export
#+begin_src go <<Types, Pr. \ref{pr:m2n}>>=
  type Tree struct {
	  start, end int
	  si, ei int
	  neighbors []string
	  mm int
	  query string
	  root *nwk.Node
  }
#+end_src
#+begin_export latex
We import \ty{nwk}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
"github.com/evolbioinf/nwk"
#+end_src
#+begin_export latex
To store a tree, we extract its string representation together with
its extent, and construct it from the string representation.
#+end_export
#+begin_src go <<Store tree, Pr. \ref{pr:m2n}>>=
  tree := new(Tree)
  //<<Extract tree string, Pr. \ref{pr:m2n}>>
  //<<Extract extent of tree, Pr. \ref{pr:m2n}>>
  //<<Construct tree, Pr. \ref{pr:m2n}>>
  trees = append(trees, tree)
#+end_src
#+begin_export latex
In order to extract the tree string, we split the input line at the
closing square bracket. If the tree has a prepended extent in square
brackets (Figure~\ref{fig:mso}), the second entry in the resulting
array is the tree string, otherwise it's the first entry.
#+end_export
#+begin_src go <<Extract tree string, Pr. \ref{pr:m2n}>>=
  arr := strings.Split(line, "]")
  hasExt := false
  if len(arr) == 2 {
	  hasExt = true
  }
  ts := arr[0]
  if hasExt {
	  ts = arr[1]
  }
#+end_src
#+begin_export latex
If the tree doesn't have an explicit extent, it extends across the
full sequence. Otherwise, its extent is the first entry in the array
after removal of the opening square bracket.
#+end_export
#+begin_src go <<Extract extent of tree, Pr. \ref{pr:m2n}>>=
  ext := seqLen
  if hasExt {
	  var e error
	  ext, e = strconv.Atoi(arr[0][1:])
	  util.Check(e)
  }
#+end_src
#+begin_export latex
We construct a new tree, set its start and end positions, and convert
the tree to its root. Then we append it to the slice of trees. At the
end we shift the start position of the next tree to a position beyond
the end of the current tree.
#+end_export
#+begin_src go <<Construct tree, Pr. \ref{pr:m2n}>>=
  tree.start = start
  tree.end = tree.start + ext - 1
  tree.query = query
  r := strings.NewReader(ts)
  sc := nwk.NewScanner(r)
  sc.Scan()
  tree.root = sc.Tree()
  start = tree.end + 1
#+end_src
#+begin_export latex
We iterate over the positions of the mutations and store them.
#+end_export
#+begin_src go <<Store positions of mutations, Pr. \ref{pr:m2n}>>=
  fields := strings.Fields(line)
  for i := 1; i < len(fields); i++ {
	  p, e := strconv.ParseFloat(fields[i], 64)
	  util.Check(e)
	  positions = append(positions, p)
  }
#+end_src
#+begin_export latex
We store a haplotype as a raw string.
#+end_export
#+begin_src go <<Store haplotype, Pr. \ref{pr:m2n}>>=
  haplotypes = append(haplotypes, line)
#+end_src
#+begin_export latex
The nearest neighbors are found by analyzing either the trees or the
haplotype distances along the sequence.
#+end_export
#+begin_src go <<Find neighbors, Pr. \ref{pr:m2n}>>=
  if treeAnalysis {
	  //<<Analyze trees, Pr. \ref{pr:m2n}>>
  } else {
	  //<<Analyze distances, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
\subsection*{Analyze Trees}
When analyzing a tree, we first visit the query leaf. Its parent's
children are the desired nearest neighbors (plus the query). The
machinery for finding the nearest neighbors starts by iterating over
the trees and calling the function \ty{findParent} on the root of each
one.
#+end_export
#+begin_src go <<Analyze trees, Pr. \ref{pr:m2n}>>=
  for _, tree := range trees {
	  findParent(tree.root, tree)
  }
#+end_src
#+begin_export latex
The function \ty{findParent} recursively traverses the tree until it
finds the query. Once the query is found, its parent is used as
starting point for adding the neighbors.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:m2n}>>=
  func findParent(v *nwk.Node, tree *Tree) {
	  if v != nil {
		  if v.Label == tree.query {
			  addNeighbors(v.Parent, tree)
		  } else {
		 	  findParent(v.Child, tree)
			  findParent(v.Sib, tree)
		  }
	  }
  }
#+end_src
#+begin_export latex
Like \ty{getParent}, the function \ty{addNeighbors} is a recursive
function that traverses the tree rooted on the query's parent and adds
all qualifying nodes.
#+end_export
#+begin_src go <<Functions, Pr. \ref{pr:m2n}>>=
  func addNeighbors(v *nwk.Node, tree *Tree) {
	  if v != nil {
		  //<<Add node? Pr. \ref{pr:m2n}>>
		  addNeighbors(v.Child, tree)
		  addNeighbors(v.Sib, tree)
	  }
  }
#+end_src
#+begin_export latex
A qualifying node is a leaf that isn't the query. If that is the case,
we append the node label to the tree's slice of neighbors.
#+end_export
#+begin_src go <<Add node? Pr. \ref{pr:m2n}>>=
  if v.Child == nil && v.Label != tree.query {
	  tree.neighbors = append(tree.neighbors,
		  v.Label)
  }
#+end_src
#+begin_export latex
\subsection*{Analyze Distances}
If instead of analyzing the trees we analyze the distances, we first
determine the start and end positions along the haplotypes that belong
to the tree. Then we find the nearest neighbors by distance.
#+end_export
#+begin_src go <<Analyze distances, Pr. \ref{pr:m2n}>>=
  //<<Find haplotype start and end indexes, Pr. \ref{pr:m2n}>>
  //<<Find distance neighbors, Pr. \ref{pr:m2n}>>
#+end_src
#+begin_export latex
To find the haplotype start and end indexes, we iterate over the trees
and adjust the end index. For this we scan the positions array, so we
store its length for later reference.
#+end_export
#+begin_src go <<Find haplotype start and end indexes, Pr. \ref{pr:m2n}>>=
  ii := 0
  np := len(positions)
  for _, tree := range trees {
	  //<<Find end index, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
The current index is the start index for this tree. We map the end of
the tree to $(0,1)$, the interval on which mutations are placed by
\ty{ms} (Figure~\ref{fig:mso}). Then we walk to the right until we
either find the end of the tree or the first mutation beyond it. The
position we have now reached is just beyond the desired one, and
identical to the start index for the next round.
#+end_export
#+begin_src go <<Find end index, Pr. \ref{pr:m2n}>>=
  tree.si = ii
  e := float64(tree.end) / float64(seqLen)
  for ii < np && positions[ii] <= e {
	  ii++
  }
  tree.ei = ii - 1
#+end_src
#+begin_export latex
Having divided the haplotypes among the trees, we can now find the
neighbors according to distance by iterating across the trees one more
time. For each tree, we calculate the distances to the query, find the
minimum distance, and add the distance neighbors.
#+end_export
#+begin_src go <<Find distance neighbors, Pr. \ref{pr:m2n}>>=
  dist := make([]int, nsam)
  for _, tree := range trees {
	  //<<Calculate distances, Pr. \ref{pr:m2n}>>
	  //<<Find minimum distance, Pr. \ref{pr:m2n}>>
	  //<<Add distance neighbors, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
We iterate over the sample, and for each member---except for the
query---calculate the distance to the query.
#+end_export
#+begin_src go <<Calculate distances, Pr. \ref{pr:m2n}>>=
  for i := 0; i < nsam; i++ {
	  if i == qi {
		  continue
	  }
	  //<<Calculate distance, Pr. \ref{pr:m2n}>>
  }
#+end_src
#+begin_export latex
A distance is the sum of mismatches along the current tree.
#+end_export
#+begin_src go <<Calculate distance, Pr. \ref{pr:m2n}>>=
  dist[i] = 0;
  for j := tree.si; j <= tree.ei; j++ {
	  c1 := haplotypes[i][j]
	  c2 := haplotypes[qi][j]
	  if c1 != c2 {
		  dist[i]++
	  }
  }
#+end_src
#+begin_export latex
We iterate over the distances to find their minimum and store that as
the mismatches for this tree.
#+end_export
#+begin_src go <<Find minimum distance, Pr. \ref{pr:m2n}>>=
  min := seqLen +1
  for i := 0; i < nsam; i++ {
	  if i == qi {
		  continue
	  }
	  if dist[i] < min {
		  min = dist[i]
	  }
  }
  tree.mm = min
#+end_src
#+begin_export latex
We store all neighbors with the minimum distance.
#+end_export
#+begin_src go <<Add distance neighbors, Pr. \ref{pr:m2n}>>=
  for i := 0; i < nsam; i++ {
	  if i != qi && dist[i] == min {
		  nei := strconv.Itoa(i+1)
		  tree.neighbors =
			  append(tree.neighbors, nei)
	  }
  }
#+end_src
#+begin_export latex
In order to merge trees with identical neighbors, we first sort the
neighbors of all trees.
#+end_export
#+begin_src go <<Merge trees, Pr. \ref{pr:m2n}>>=
  //<<Sort neighbors, Pr. \ref{pr:m2n}>>
  //<<Merge trees with identical neighbors, Pr. \ref{pr:m2n}>>
#+end_src
#+begin_export latex
We sort the neighbors by calling the library function for sorting
strings.
#+end_export
#+begin_src go <<Sort neighbors, Pr. \ref{pr:m2n}>>=
  for _, tree := range trees {
	  sort.Strings(tree.neighbors)
  }
#+end_src
#+begin_export latex
We import \ty{sort}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "sort"
#+end_src
#+begin_export latex
Whenever we find a tree with the same neighbors as its left hand
neighbor, we merge them by extending the end position and summing the
mismatches.
#+end_export
#+begin_src go <<Merge trees with identical neighbors, Pr. \ref{pr:m2n}>>=
  c := 0
  for i := 1; i < len(trees); i++ {
	  if slices.Equal(trees[c].neighbors,
		  trees[i].neighbors) {
			  trees[c].end = trees[i].end
			  trees[c].mm += trees[i].mm
		  } else {
			  c++
			  trees[c] = trees[i]
		  }
  }
  trees = trees[0:c+1]
#+end_src
#+begin_export latex
We import \ty{slices}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "slices"
#+end_src
#+begin_export latex
We print the query name as the header, then we iterate over the
trees. For each tree, we calculate the mismatches per site. Then we
print its start, end, mismatches per site, and the query's neighbors.
#+end_export
#+begin_src go <<Print neighbors, Pr. \ref{pr:m2n}>>=
  mm := 0.0
  fmt.Printf(">%s\n", query)
  for _, tree := range trees {
	  //<<Calculate mismatches per site, Pr. \ref{pr:m2n}>>
	  fmt.Printf("%d\t%d\t%.4f\t%s",
		  tree.start+1, tree.end+1, mm,
		  tree.neighbors[0])
	  for _, neighbor := range tree.neighbors[1:] {
		  fmt.Printf(" %s", neighbor)
	  }
	  fmt.Printf("\n")
  }
#+end_src
#+begin_export latex
We import \ty{fmt}.
#+end_export
#+begin_src go <<Imports, Pr. \ref{pr:m2n}>>=
  "fmt"
#+end_src
#+begin_export latex
If we used tree analysis, we have not kept track of the mismatches, in
which case we set the number of mismatches per site to -1. Otherwise
we simply divide the mismatches by the tree extent.
#+end_export
#+begin_src go <<Calculate mismatches per site, Pr. \ref{pr:m2n}>>=
  mm = -1
  if !treeAnalysis {
	  ext := tree.end - tree.start + 1
	  mm = float64(tree.mm) / float64(ext)
  }
#+end_src
#+begin_export latex
We've finished \ty{ms2nn}, let's test it.

\section{Testing \ty{ms2nn}}
Our program for testing \ty{ms2nn} has hooks for imports and the
testing logic.
\bpr{ms2nn_test}{pr:m2nt}
#+end_export
#+begin_src go <<ms2nn_test.go>>=
  package main

  import (
	  "testing"
	  //<<Testing imports, Pr. \ref{pr:m2nt}>>
  )

  func TestMs2nn(t *testing.T) {
	  //<<Testing, Pr. \ref{pr:m2nt}>>
  }
#+end_src
#+begin_export latex
\epr
To test \ty{ms2nn}, we construct a set of tests and then run each one
in turn.
#+end_export
#+begin_src go <<Testing, Pr. \ref{pr:m2nt}>>=
  var tests []*exec.Cmd
  //<<Construct tests, Pr. \ref{pr:m2nt}>>
  for i, test := range tests {
	  //<<Run test, Pr. \ref{pr:m2nt}>>
  }
#+end_src
#+begin_export latex
We construct two tests with queries 1 and 2, then repeat with tree
merging. All tests run on the input file \ty{test.ms}.
#+end_export
#+begin_src go <<Construct tests, Pr. \ref{pr:m2nt}>>=
  p := "./ms2nn"
  f := "test.ms"
  test := exec.Command(p, "-q", "1", f)
  tests = append(tests, test)
  test = exec.Command(p, "-q", "2", f)
  tests = append(tests, test)
  test = exec.Command(p, "-q", "1", "-t", f)
  tests = append(tests, test)
  test = exec.Command(p, "-q", "2", "-t", f)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We import \ty{exec}.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:m2nt}>>=
  "os/exec"
#+end_src
#+begin_export latex
For a given test we compare the output we get to the output we want,
which is contained in files \ty{r1.txt} and \ty{r2.txt}.
#+end_export
#+begin_src go <<Run test, Pr. \ref{pr:m2nt}>>=
  get, err := test.Output()
  if err != nil {
	  t.Error(err)
  }
  f = "r" + strconv.Itoa(i + 1) + ".txt"
  want, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal(get, want) {
	  t.Errorf("get:\n%s\nwant:\n%s\n", get, want)
  }
#+end_src
#+begin_export latex
We import \ty{strconv}, \ty{os}, and \ty{bytes}.
#+end_export
#+begin_src go <<Testing imports, Pr. \ref{pr:m2nt}>>=
  "strconv"
  "os"
  "bytes"
#+end_src

#+begin_export latex
\section{Testing \ty{alfy}: \ty{testAlfy.sh}}
To simplify testing, we write the short script \ty{testAlfy.sh} that
implements the steps sketched in Figure~\ref{fig:ms}. Inside
\ty{testAlfy.sh}, we set parameters, generate haplotypes, analyze the
haplotypes with \ty{ms2nn}, analyze them with \ty{alfy}, and compare
the results of \ty{alfy} to the ground truth.
\bpr{testAlfy.sh}{pr:ta}
#+end_export
#+begin_src sh <<testAlfy.sh>>=
  ##<<Set parameters, Pr. \ref{pr:ta}>>
  ##<<Generate haplotypes, Pr. \ref{pr:ta}>>
  ##<<Analyze haplotypes with \ty{ms2nn}, Pr. \ref{pr:ta}>>
  ##<<Analyze haplotypes with \ty{alfy}, Pr. \ref{pr:ta}>>
  ##<<Compare \ty{alfy} results to ground truth, Pr. \ref{pr:ta}>>
#+end_src
#+begin_export latex
\epr We set the parameters to arbitrary initial values, which can of
course be changed by the user to explore other combinations. Here we
start with a sample size of $n=5$, a population mutation rate of
$\theta=100$, a population recombination rate of $\rho=1$, and $10^4$
recombining sites.
#+end_export
#+begin_src sh <<Set parameters, Pr. \ref{pr:ta}>>=
  n=5
  theta=100
  rho=1
  len=10000
#+end_src
#+begin_export latex
To generate the haplotypes, we run \ty{ms} on the parameters with tree
printing (\ty{-T}) and save the result in the file \ty{ms.out}.
#+end_export
#+begin_src sh <<Generate haplotypes, Pr. \ref{pr:ta}>>=
  ms $n 1 -t $theta -r $rho $len -T > ms.out
#+end_src
#+begin_export latex
We analyze the contents of \ty{ms.out} with \ty{ms2nn} and save the
result in file \ty{ms.nn}.
#+end_export
#+begin_src sh <<Analyze haplotypes with \ty{ms2nn}, Pr. \ref{pr:ta}>>=
  ms2nn -q 1 ms.out > ms.nn
#+end_src
#+begin_export latex
The program \ty{alfy} works on a pair of query/subject DNA sequences
rather than haplotypes. So we convert the haplotypes do DNA sequences
using \ty{ms2dna} and convert the sequence names from ``S1'', ``S2'',
and so on to the original 1, 2,... before saving the sequences in
\ty{ms.fasta}. We split the contents of \ty{ms.fasta} into query and
subject sequences, to which we apply \ty{alfy} and save the result to
\ty{ms.alfy}.
#+end_export
#+begin_src sh <<Analyze haplotypes with \ty{alfy}, Pr. \ref{pr:ta}>>=
  ms2dna ms.out | tr -d S > ms.fasta
  getSeq 1 ms.fasta > q.fasta
  getSeq -c 1 ms.fasta > s.fasta
  alfy -M -i q.fasta -j s.fasta > ms.alfy
#+end_src
#+begin_export latex
To compare the contents of \ty{ms.nn} and \ty{ms.alfy}, we simply
paste them next to each other.
#+end_export
#+begin_src sh <<Compare \ty{alfy} results to ground truth, Pr. \ref{pr:ta}>>=
  paste ms.alfy ms.nn
#+end_src
